archivo_abierto=open("C:\\Users\\jcard\\OneDrive - Universidad de Colima\\Documentos\\Actividades\\fime.txt")
archivo_abierto.write("Esto se escribe en el archivo\n")
archivo_abierto.write("Esto tambien\n")
archivo_abierto.write("Mira puedo escribir \"comillas\"\n")
archivo_abierto.write("Gracias a la diagonal invertida: \ \n")
archivo_abierto.close()
